'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { FileText, FileSpreadsheet, FileType2, Download, Eye, Loader2, AlertTriangle, Lock } from 'lucide-react'
import { PageContainer, PageHeader } from '@/components/page-header'
import { Panel } from '@/components/panel'
import { useToast } from '@/components/toast'
import { getDeliverables, getTask, isAuthed, downloadDeliverable, type BackendDeliverable } from '@/lib/api'
import { openAuth } from '@/components/auth-modal'
import { cn } from '@/lib/utils'

const iconMap: Record<string, { icon: typeof FileText; tone: string }> = {
  docx: { icon: FileText, tone: 'border-info/40 bg-info/10 text-info' },
  xlsx: { icon: FileSpreadsheet, tone: 'border-safe/40 bg-safe/10 text-safe' },
  pdf: { icon: FileType2, tone: 'border-danger/40 bg-danger/10 text-danger' },
  pid: { icon: Eye, tone: 'border-warning/40 bg-warning/10 text-warning' },
}

interface Directive {
  filename: string
  file_type: string
  sha256: string
  generated: string
}

export default function DeliverablesPage() {
  const toast = useToast()
  const [list, setList] = useState<Directive[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [busyFile, setBusyFile] = useState('')

  useEffect(() => {
    let active = true
    const taskId = sessionStorage.getItem('vyoma_task_id')

    if (!isAuthed()) {
      setError('Sign in to the local backend to view deliverables.')
      setLoading(false)
      return
    }
    if (!taskId) {
      setError('No inspection has been run yet. Start an inspection to generate deliverables.')
      setLoading(false)
      return
    }

    Promise.all([getDeliverables(taskId), getTask(taskId)])
      .then(([resp, task]) => {
        if (!active) return
        const t = new Date(task.updated_at ?? task.created_at ?? '')
        const displayTime = Number.isNaN(t.getTime())
          ? (task.updated_at ?? task.created_at ?? '—')
          : t.toLocaleString(undefined, { hour12: false })
        setList(
          resp.deliverables.map((d: BackendDeliverable) => ({
            filename: d.filename,
            file_type: d.file_type,
            sha256: d.sha256,
            generated: displayTime,
          })),
        )
      })
      .catch((err: unknown) => {
        if (!active) return
        setError(err instanceof Error ? err.message : 'Could not load deliverables.')
      })
      .finally(() => active && setLoading(false))

    return () => {
      active = false
    }
  }, [])

  const download = async (d: Directive) => {
    setBusyFile(d.filename)
    try {
      await downloadDeliverable(sessionStorage.getItem('vyoma_task_id')!, d.filename)
      toast.push({ kind: 'success', title: 'Download started', message: d.filename })
    } catch (err) {
      toast.push({
        kind: 'error',
        title: 'Download failed',
        message: err instanceof Error ? err.message : 'Could not download the deliverable.',
      })
    } finally {
      setBusyFile('')
    }
  }

  return (
    <PageContainer>
      <PageHeader
        title="Inspection Deliverables"
        subtitle="Reports and analysis outputs generated by the local KAVACH pipeline for the current task"
      />

      {loading && (
        <Panel className="flex flex-col items-center gap-3 p-12">
          <Loader2 className="size-6 animate-spin text-info" />
          <p className="text-sm text-muted-foreground">Loading deliverables…</p>
        </Panel>
      )}

      {!loading && error && (
        <Panel className="flex flex-col items-center gap-4 border-warning/40 bg-warning/5 p-10 text-center">
          <AlertTriangle className="size-8 text-warning" />
          <div>
            <h3 className="text-lg font-bold text-foreground">Deliverables unavailable</h3>
            <p className="mt-1 text-sm text-muted-foreground">{error}</p>
          </div>
          {!isAuthed() ? (
            <button
              onClick={openAuth}
              className="mt-2 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
            >
              Sign In
            </button>
          ) : (
            <Link
              href="/new-inspection"
              className="mt-2 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
            >
              Start an Inspection
            </Link>
          )}
        </Panel>
      )}

      {!loading && !error && list.length === 0 && (
        <Panel className="p-10 text-center">
          <p className="text-sm text-muted-foreground">
            No deliverables recorded for the current task. Deliverables are generated after a
            completed safety analysis.
          </p>
        </Panel>
      )}

      {!loading && !error && list.length > 0 && (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {list.map((d) => {
            const key = d.file_type === 'docx' ? 'docx' : d.file_type === 'xlsx' ? 'xlsx' : 'pdf'
            const { icon: Icon, tone } = iconMap[key] ?? { icon: FileType2, tone: 'border-border bg-secondary text-muted-foreground' }
            return (
              <Panel key={d.filename} corners className="flex flex-col p-5 transition-colors hover:bg-card-elevated">
                <div className={cn('flex size-12 items-center justify-center rounded-md border', tone)}>
                  <Icon className="size-6" />
                </div>
                <h3 className="mt-4 break-all text-sm font-semibold text-foreground">{d.filename}</h3>
                <p className="mt-1 text-sm text-muted-foreground">
                  Generated by the KAVACH verification pipeline.
                </p>

                <dl className="mt-4 space-y-1.5 border-t border-border pt-3 font-mono text-xs">
                  <div className="flex justify-between gap-2">
                    <dt className="text-muted-foreground">Type</dt>
                    <dd className="text-foreground">{d.file_type}</dd>
                  </div>
                  <div className="flex justify-between gap-2">
                    <dt className="text-muted-foreground">Sha-256</dt>
                    <dd className="truncate text-foreground" title={d.sha256}>
                      {d.sha256.slice(0, 12)}…
                    </dd>
                  </div>
                  <div className="flex justify-between gap-2">
                    <dt className="text-muted-foreground">Generated</dt>
                    <dd className="text-foreground">{d.generated}</dd>
                  </div>
                </dl>

                <div className="mt-4 flex gap-2">
                  <button
                    onClick={() => download(d)}
                    disabled={busyFile === d.filename}
                    className="flex flex-1 items-center justify-center gap-1.5 rounded-md bg-primary py-2 text-xs font-semibold text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-60"
                  >
                    {busyFile === d.filename ? (
                      <Loader2 className="size-3.5 animate-spin" />
                    ) : (
                      <Download className="size-3.5" />
                    )}{' '}
                    {d.file_type}
                  </button>
                </div>
              </Panel>
            )
          })}
        </div>
      )}

      <Panel className="mt-6 flex flex-col items-start gap-3 p-5 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-medium text-foreground">Authenticated downloads</p>
          <p className="text-xs text-muted-foreground">
            Each deliverable is fetched directly from the backend with the signed session token. Files are
            served only to accounts that can read the task.
          </p>
        </div>
        <span className="flex items-center gap-2 rounded-md border border-info/25 bg-info/10 px-3 py-2 font-mono text-xs text-info">
          <Lock className="size-3.5" /> JWT-protected
        </span>
      </Panel>
    </PageContainer>
  )
}